#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Sat Jan 11 18:28:24 UTC 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail

echo "xvhdl --work xil_defaultlib Hast_IP.vhd"
#xvhdl --incr --relax  --work xil_defaultlib Hast_IP.vhd 2>&1 | tee compile.log
xvhdl "../src/IP/Hast_IP.vhd" 2>&1 | tee compile.log
xvhdl "../src/IP/Hast_IP_Wrapper.vhd" 2>&1 | tee compile.log

echo "xvlog --incr --relax -L axi_vip_v1_1_6 -L xilinx_vip -prj hastip_tb_vlog.prj"
xvlog --incr --relax -L axi_vip_v1_1_6 -L xilinx_vip -prj hastip_tb_vlog.prj 2>&1 | tee compile.log


